src/core/urls.py
from django.conf.urls import url, include
from django.contrib.auth import views as auth_views
from . import views as core_views

urlpatterns = [
    url(r'^$', core_views.home, name='home'),
    url(r'^login/$', auth_views.login, {'template_name': 'login.html'}, name='login'),
    url(r'^logout/$', auth_views.logout, {'next_page': 'login'}, name='logout'),
    url(r'^signup/$', core_views.signup, name='signup'),
    url(r'^account_activation_sent/$', core_views.account_activation_sent, name='account_activation_sent'),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        core_views.activate, name='activate'),
]

src/posts/urls.py
from django.conf.urls import url
from .views import (
	post_list,
	post_create,
	post_detail,
	post_update,
	post_delete
	)


urlpatterns = [
    url(r'^$', post_list, name= 'list'),
    url(r'^create$', post_create),
    url(r'^(?P<slug>[\w-]+)/$', post_detail, name ='detail'),
    url(r'^(?P<slug>[\w-]+)/edit$', post_update, name = 'update'),
    url(r'^(?P<slug>[\w-]+)/delete$', post_delete, name='delete'),
]

src/trydjango19/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url, include
from django.contrib import admin
#from src.core import views as core_views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^core/', include('core.urls', namespace='core')),
    url(r'^posts/', include('posts.urls', namespace='posts')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/posts/models.py
from __future__ import unicode_literals
from django.db import models
from django.core.urlresolvers import reverse
from django.db.models.signals import pre_save
from django.utils.text import slugify
from django.conf import settings
from django.utils import timezone

# Create your models here.

class PostManager(models.Manager):
	def active(self, *args, **kwargs):
		return super(PostManager, self).filter(draft=False).filter(publish__lte=timezone.now())

def upload_location(instance, filename):
	# filebase, extension = filename.split(".")
	# reverseeturn "%s/%s.%s" %(instance.id, instance.id, extension)
	# import pdb
	# pdb.set_trace()
	return "%s/%s" %(instance.slug, filename)

class Post(models.Model):
	user = models.ForeignKey(settings.AUTH_USER_MODEL, default = 1)
	title = models.CharField(max_length = 120)
	slug = models.SlugField(unique=True)
	image = models.ImageField(upload_to = upload_location,
			null=True, 
			blank=True,
			width_field = "width_field",
			height_field = "height_field")
	height_field = models.IntegerField(default=0)
	width_field = models.IntegerField(default=0)
	content = models.TextField()
	draft = models.BooleanField(default= False)
	publish = models.DateField(auto_now=False, auto_now_add= False)
	updated = models.DateTimeField(auto_now = True, auto_now_add = False)
	timestamp = models.DateTimeField(auto_now = False, auto_now_add = True)

	objects = PostManager()

	def __unicode__(self):
		return self.title

	def __str__(self):
		return self.title

	def get_absolute_url(self):
		return reverse("posts:detail",kwargs={"slug":self.slug})

	class Meta:
		ordering = ["-timestamp", "-updated"]

def create_slug(instance, new_slug=None):
	slug=slugify(instance.title)
	if new_slug is not None:
		slug = new_slug
	qs = Post.objects.filter(slug=slug).order_by("-id")
	exists = qs.exists()
	if exists:
		new_slug = "%s-%s" %(slug, qs.first().id)
		return create_slug(instance, new_slug=new_slug)
	return slug

def  pre_save_post_receiver(sender, instance, *args, **kwargs):
	if not instance.slug:
		instance.slug = create_slug(instance)

pre_save.connect(pre_save_post_receiver, sender=Post)

src/posts/forms.py
from django import forms
from .models import Post

class PostForm(forms.ModelForm):
	class Meta:
		model = Post
		fields = [
			"title",
			"content",
			"image",
			"draft",
			"publish"
		]

src/posts/views.py
from urllib import quote_plus
from django.contrib import messages
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.shortcuts import render, get_object_or_404, redirect
from .models import Post
from .forms import PostForm
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.utils import timezone
from django.db.models import Q
import requests
import json
# Create your views here.

def post_create(request):
	if not request.user.is_staff or not request.user.is_superuser:
		raise Http404
	form = PostForm(request.POST or None, request.FILES or None)
	if form.is_valid():
		instance = form.save(commit=False)
		instance.user = request.user
		# print form.cleaned_data.get("title")
		instance.save()
		messages.success(request, "Successfuly Created")
		return HttpResponseRedirect(instance.get_absolute_url())
	# elif form.errors:
	# 	messages.error(request, "Not Successfuly Created")
	# else:
	# 	pass

	# if request.method == "POST":
	# 	print request.POST.get("title")
	# 	Post.objects.create(title = "title 1")
	context = {
		"form" : form,
	}
	return render(request, "post_form.html", context)

def post_detail(request,slug = None):
	# instance = Post.objects.get(id=3)
	instance = get_object_or_404(Post, slug = slug)
	if instance.publish > timezone.now().date() or instance.draft:
		if not request.user.is_staff or not request.user.is_superuser:
			raise Http404

	share_string = quote_plus(instance.content)
	context = { 
		"title" : instance.title,
		"instance" : instance,
		"share_string" : share_string
	}
	return render(request, "post_detail.html", context)

def post_list(request):
	today = timezone.now().date()
	queryset_list = Post.objects.active()#.order_by("-timestamp")
	if request.user.is_staff or request.user.is_superuser:
		queryset_list = Post.objects.all()

	query = request.GET.get("q")
	if query:
		queryset_list = queryset_list.filter(
			Q(title__icontains=query)|
			Q(content__icontains=query)|
			Q(user__first_name__icontains=query)|
			Q(user__last_name__icontains=query)
			).distinct()

	paginator = Paginator(queryset_list, 5) # Show 25 contacts per page
	page_request_var = "page"
	page = request.GET.get(page_request_var)
	try:
		queryset = paginator.page(page)
	except PageNotAnInteger:
        # If page is not an integer, deliver first page.
		queryset = paginator.page(1)
	except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
		queryset = paginator.page(paginator.num_pages)

	url="https://maps.googleapis.com/maps/api/place/textsearch/json?query=restaurants+in+Bangalore&key=AIzaSyA_NzQ4XHkIQSVS4dd00SFkTsCSL7fx3IQ"
	r = requests.get(url)
	parson = json.loads(r.text)
	op = parson['results'][1]['formatted_address']


	context = {
			"object_list" : queryset,
			"title" : "List",
			"page_request_var" : page_request_var,
			"today" : today,
			"op" : op
		}
	# if request.user.is_authenticated():
	# 	context = { 
	# 		"title" : "authenticated"
	# 	}
	# else:
	# 	context = {
	# 		"title" : "not authorized"
	# 	}
	return render(request, "post_list.html", context)


def post_update(request,slug = None):
	if not request.user.is_staff or not request.user.is_superuser:
		raise Http404
	instance = get_object_or_404(Post, slug = slug)
	form = PostForm(request.POST or None, request.FILES or None, instance=instance )
	if form.is_valid():
		instance = form.save(commit=False)
		instance.save()
		messages.success(request, "Item Saved")
		return HttpResponseRedirect(instance.get_absolute_url())
	context = {
		"title" : instance.title,
		"instance" : instance,
		"form" : form,
	}
	return render(request, "post_form.html", context)

def post_delete(request,slug = None):
	instance = get_object_or_404(Post, slug = slug)
	instance.delete()
	messages.success(request,"Successfully Deleted")
	return redirect("posts:list")

src/templates/account_activation_email.html
{% autoescape off %}
Hi {{ user.username }},

Please click on the link below to confirm your registration:

http://{{ domain }}{% url 'core:activate' uidb64=uid token=token %}

{% endautoescape %}

src/templates/account_activation_invalid.html
{% extends 'base_core.html' %}

{% block content %}
  <p>The confirmation link was invalid, possibly because it has already been used.</p>
{% endblock %}

src/templates/account_activation_sent.html
{% extends 'base_core.html' %}

{% block content %}
  <p>Please confirm your email address to complete the registration. </p>
{% endblock %}

src/templates/base.html
{% load staticfiles %}
<DOCTYPE html>
<html>

<head> <title> {% block head_title %} Try Django 1.9 {% endblock head_title %}</title></head>
<link rel="stylesheet" type="text/css" href="{% static "css/base.css"%}" />
<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">


<style> 
{% block style %}
{% endblock style %}
</style>

<body>
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_GB/sdk.js#xfbml=1&version=v2.8";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

{% include "message_display.html" %}
<div class="container">
 {% block content %}  {% endblock content %}
</div>

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
</body>
</html>

src/templates/base_core.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>{% block title %}Simple is Better Than Complex{% endblock %}</title>
  </head>
  <body>
    <header>
      <h1>My Site</h1>
      {% if user.is_authenticated %}
        <a href="{% url 'core:logout' %}">logout</a>
      {% else %}
        <a href="{% url 'core:login' %}">login</a> / <a href="{% url 'core:signup' %}">signup</a>
      {% endif %}
      <hr>
    </header>
    <main>
      {% block content %}
      {% endblock %}
    </main>
  </body>
</html>

src/templates/home.html
{% extends 'base_core.html' %}

{% block content %}
  <h2>Welcome, {{ user.get_full_name }} <small>{{ user.username }}</small>!</h2>
  <p>Thanks for confirming your email address!</p>
{% endblock %}

src/templates/login.html
{% extends 'base_core.html' %}

{% block content %}
  <h2>Log in to My Site</h2>
  {% if form.errors %}
    <p style="color: red">Your username and password didn't match. Please try again.</p>
  {% endif %}
  <form method="post">
    {% csrf_token %}
    <input type="hidden" name="next" value="{{ next }}" />
    {% for field in form %}
      <p>
        {{ field.label_tag }}<br>
        {{ field }}<br>
        {% for error in field.errors %}
          <p style="color: red">{{ error }}</p>
        {% endfor %}
        {% if field.help_text %}
          <p><small style="color: grey">{{ field.help_text }}</small></p>
        {% endif %}
      </p>
    {% endfor %}
    <button type="submit">Log in</button>
    <a href="{% url 'core:signup' %}">New to My Site? Sign up</a>
  </form>
{% endblock %}

src/templates/message_display.html
{% if messages %}
<div class="messages">
 <ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
 </ul>
</div>
{% endif %}

src/templates/post_detail.html
{% extends "base.html" %}
{% load urlify %}
{% block head_title %} {{ instance.title }} | {{ block.super }} {% endblock head_title %}


{% block content %}
<div class="col-sm-6 col-sm-offset-3">
{% if instance.image %}
<img src="{{ instance.image.url }}" class="img-responsive" />
{% endif %}
<h1> {{ title }} <small>{% if instance.draft %}<span style="color: red;"> Draft </span> {% endif %}{{ instance.publish }}</small></h1>
{% if instance.user.get_full_name %}
<p>Author : {{ instance.user }} </p>
{% endif %}
<!-- {{ instance.content | truncatechars:30 | urlify }} -->

<!-- <p>
<div class="fb-like" data-href="https://developers.facebook.com/docs/plugins/" data-layout="button_count" data-action="like" data-size="small" data-show-faces="true" data-share="true"></div>
</p>

<p>
<a href="https://www.facebook.com/sharer/sharer.php?u={{ request.build_absolute_url }}">
Facebook
</a>

<a href="https://twitter.com/home?status={{ share_string }}%20{{ request.build_absolute_url }}">
Twitter
</a>

<a href='https://plus.google.com/share?url={{ request.build_absolute_url }}'>

<a href="https://www.linkedin.com/shareArticle?mini=true&url={{ request.build_absolute_url }}&title={{ instance.title }}&summary={{ share_string }}&source={{ request.build_absolute_url }}">
Linkedin
</a>

<a href="http://www.reddit.com/submit?url={{ request.build_absolute_url }}/&title={{ share_string }}">Reddit</a>
</p> -->
<div class="row">
<div class="col-sm-12">

	{{ instance.content|linebreaks }}<br/>
<hr/>
<br/>

<div class="fb-comments" data-href="{{ request.build_absolute_url }}" data-numposts="5"></div>
</div>
</div>
</div>
{% endblock content %}

src/templates/post_form.html
{% extends "base.html" %}

{% block content %}
<!-- 	{{ block.super }} -->
<div class="col-sm-6 col-sm-offset-3">
 <h1>Form</h1>
<form method="POST" action="" enctype="multipart/form-data"> {% csrf_token %}
	{{ form.as_p }}	
 <input type="SUBMIT" class="btn btn-default" value="Create Post"/>
</form>
</div>
{% endblock content %}

src/templates/post_list.html
{% extends "base.html" %}

{% block content %}

<div class="col-sm-6 col-sm-offset-3">
	<h1>{{ title }}</h1>

<form method="GET" action="">
  <input type="text" name="q" placeholder="Search posts" value="{{ request.GET.q }}" />
  <input type="submit" name="Search" />
</form>

{% for obj in object_list %}
<div class="row">
  <div class="col-sm-12">
    <div class="thumbnail">
    {% if obj.image %}
     <img src="{{ obj.image.url }}" class="img-responsive" />
     {% endif %}
      <div class="caption">
       <!-- <h3><a href='{{ obj.get_absolute_url }}'>{{ obj.title }}</a><small> {{ obj.timestamp|timesince }} ago</small> </h3> -->
       {% if obj.draft %}<h3>DRAFT</h3>{% endif %}  {% if obj.publish > today %}<h3>Future Post</h3>{% endif %}
        <h3><a href='{{ obj.get_absolute_url }}'>{{ obj.title }}</a><small> {{ obj.publish }} </small> </h3>
        {% if obj.user.get_full_name %}
        <p> Author : {{ obj.user.get_full_name }}
        {% endif %}
        <p>{{ obj.content|linebreaks|truncatechars:120 }}</p>
        <p>{{ op }}</p>
        <p><a href="{{ obj.get_absolute_url }}" class="btn btn-primary" role="button">View</a></p>
      </div>
    </div>
    </div>
   <hr/>
  </div>
  {% endfor %}

<div class="pagination">
    <span class="step-links">
        {% if object_list.has_previous %}
            <a href="?{{ page_request_var }}={{ object_list.previous_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %} ">previous</a>
        {% endif %}

        <span class="current">
            Page {{ object_list.number }} of {{ object_list.paginator.num_pages }}.
        </span>

        {% if object_list.has_next %}
            <a href="?{{ page_request_var }}={{ object_list.next_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">next</a>
        {% endif %}
    </span>
</div>

</div>
{% endblock content %}

src/templates/signup.html
{% extends 'base_core.html' %}

{% block content %}
  <h2>Sign up</h2>
  <form method="post">
    {% csrf_token %}
    {% for field in form %}
      <p>
        {{ field.label_tag }}<br>
        {{ field }}
        {% if field.help_text %}
          <small style="color: grey">{{ field.help_text }}</small>
        {% endif %}
        {% for error in field.errors %}
          <p style="color: red">{{ error }}</p>
        {% endfor %}
      </p>
    {% endfor %}
    <button type="submit">Sign up</button>
  </form>
{% endblock %}